--================================SectionA==============================
--Count the total number of customers, products, and orders in the database (three separate queries or one with
--three columns).
Select
  (Select COUNT(*) From Customer) As TotalCustomers,
  (Select COUNT(*) From Product) As TotalProducts,
  (Select COUNT(*) FROM OrderItem) As TotalOrders;


--Find the cheapest and most expensive products. Show MinPrice and MaxPrice
Select
  MIN(Price) AS MinPrice,
  MAX(Price) AS MaxPrice
From Products;

--What is the average price of all products? Round to 2 decimal places.
select
  ROUND(AVG(Price),2) As AvgPrice
From Products;

--What is the total stock quantity across all products?
Select 
  Sum(StockQty) AS TotalStock
From Product

--How many distinct cities do customers live in (ignoring NULL)?
Select
  Count(DisTINCT City) AS DistinctCities
From Customer;

--How many distinct categories of products are there?
Select 
  COUNT(DISTINCT Category) As DistinctCategories
From Product;

--How many customers have a recorded city? How many do not? (Two queries.)
--Query 1

Select Count(City) As WithCity From Customer;

--Query2
Select Count(*) As WithoutCity From Customer Where City IS NULL;


--Find the earliest and latest order date in the system
Select 
  Min (OrderDate) As EarliestOrder,
  MAX(OrderDate) As LatestOrder
From OrderItem;

--Compute the total revenue from all orders. Revenue per row = Quantity * Price; total = SUM of all rows. (Hint: JOIN
--OrderItem with Product.)

Select 
  Sum(o.Quantity*p.Price) As TotalRevenue
From OrderItem o
Join Product p ON o.ProdID=p.ProID;


--Compute the average quantity per order (average of Quantity column in OrderItem). Round to 2 decimals.
Select 
  Round(AVG(Quantity),2) AS AvgQuantity
From OrderItem;

--==========================================SectionB===================================

--Number of customers in each city. Sort by count descending
Select
 City,
 Count(*) AS NumCustomers
From Customer
Group BY City
ORDER BY NumCustomers DESC,

--Number of products in each category. Sort by count descending
Select
 Category,
 Count(*) As NumProducts
From Product
  Group BY Category
  Order BY NumProducts DESC;


--For each product category, find the average, minimum, and maximum price. Sort by average price descending
Select
 Category,
 Round(AVG(Price),2) AS AvgPrice,
 MIN(Price) AS MinPrice,
 Max(Price) AS MaxPrice
From Product
Group BY Category
Order BY AvgPrice DESC

--Total stock quantity per category. Sort by total descending.
Select 
 Category,
 Sum(StockQty) As TotalStock
From Product
Group BY Category
Order BY TotalStock;

--Number of orders placed in each year. Show Year and NumOrders, sorted by year.
Select
  YEAR(OrderDate) AS OrderYear,
  COUNT(*) AS NumOrders
From OrderItem
Group BY Year(OrderDate)
Order BY OrderYear;

--Number of orders placed each month of 2024. Show Month (1–12) and NumOrders, sorted by month
Select
 Month(OrderDate) As Month,
 COUNT(*) As NumOrders
From OrderItem
Where Year(OrderDate)=2024
Group BY MONTH(OrderDate)
ORDER BY Month;

--Find product categories where the average price is greater than 5,000
Select
  Category,
  AVG(Price) As AvgPrice
From Product
Group BY Category
Having AVG(Price)>5000;

--Find cities with more than 1 customer (exclude NULL city). (WHERE + GROUP BY + HAVING.)
Select
 City,
 Count(*) AS NumCustomers
From Customers
Where City IS NOT NULL
GROUP BY City
Having Count(*)>1
ORDER BY NumCustomers DESC;


--For each customer, count how many orders they have placed. Include customers with zero orders
Select
 c.CustID,c.CustName,
 Count(o.OrderID) AS NumOrders
From Customer c
Left JOIN OrderItem o ON c.CustID=o.CustID
Group BY c.CustID,c.CustName;

--Total quantity sold for each product. Show ProdName and TotalQty, sorted by TotalQty descending. Include
--products that have never been sold
Select 
 p.ProdID,p.ProdName,
 Sum(o.Quantity) As TotalQty
From Product p
Left JOIN OrderItem o ON p.ProdID=o.ProdID
Group BY p.ProdID,p.ProdName
ORDER BY TotalQTY DESC


--Total revenue (Quantity * Price) per product category. Sort by revenue descending
Select
  p.Category,
  Sum(o.Quantity*p.Price) AS Revenue
From OrderItem o
JOIN Product p ON o.ProdID=p.ProdID
GROUP BY p.Category
ORDER BY Revenue DESC;

--List customers whose total spend exceeds 50,000. Show CustName and TotalSpend
Select
  c.CustID,
  c.CustName,
  Sum(o.Quantity*p.Price) As TotalSpend
From Customer c
JOIN OrderItem o ON c.CustID=o.CustID
JOIN Product p ON o.ProdID=p.ProdID
Group BY C.CustID,c.CustName
Having Sum(o.Quantity*p.Price) >50000


--For each city, count the number of customers and total revenue generated by them. Include only cities with more
--than 1 customer
Select 
 c.City,
 COUNT(DISTINCT c.CustID) AS NumCustomers,
 Sum(o.Quantity*p.Price) As TotalRevenue
From Customer c
JOIN OrderItem o ON p.ProdID=o.ProdID
Group BY p.ProdID,p.ProdName
ORDER BY TotalQty DESC
LIMIT 3;

--For each year, compute the total revenue. Show Year and Revenue, sorted by year.
Select 
  Year(o.OrderDate)AS OrderYear,
  SUM(o.Quantity*p.Price) AS Revenue
From OrderItem o
Join Product p ON o.ProdID=p.ProdID
Group BY Year(o.OrderDate)
Order BY OrderYear;


--==================================Assesment Problem=======================

--How many students and how many courses are there
Select
 (Select COUNT(*) From Student) As TotalStudents,
 (Select COUNT(*) FROM Course)As  TotalCourses;

--How many distinct cities do students come from
Select  
   COUNT(DISTINCT City) AS DistinctCities
From Student;

--Compute the average, minimum, and maximum Marks across all enrollments.
Select
 AVG(Marks) AS AVGMarks,
 MIN(Marks) AS MinMarks,
 MAX(Marks) AS MaxMarks
From Enrollment;


--Number of students in each city. Sort by count descending. Include the NULL-city group at the end.
Select
 City,
 COUNT(*) AS NumStudents
From Student
Group BY City
ORDER BY NumStudents DESC

--Number of courses offered by each department, sorted by count descending.
Select 
 Department,
 COUNT(*) AS NumCourses
From Course
Group BY Department
Order BY NumCourses DESC;

--For each course, show CourseName, the number of students enrolled, and the average marks. Sort
--by average marks descending.
Select
 c.CourseName,
 Count(e.StudentID) AS NumStudents,
 AVG(e.Marks) AS AvgMarks
From Course c
Join Enrollment e ON c.CourseID=e.CourseIC
Group BY c.CourseName
ORDER BY AvgMarks DESC;


--List courses with an average marks above 80. Show CourseName and AvgMarks

Select 
 c.CourseName,
 AVG(e.Marks) AS AVG Marks
From Course c
Join Enrollment e ON c.CourseID=e.CourseID
Group BY c.CourseName
Having AVG(e.Marks)>80;

--Total fee revenue per department, assuming each enrolled student paid the course fee. Show
--Department and TotalRevenue, sorted descending

Select 
 c.Department,
 Sum(c.Fee) AS TotalRevenue
From Course c
Join Enrollment e ON c.courseID=e.CourseID
Group BY c.Department
Order BY TotalRevenue DESC;


--For each student, show how many courses they are enrolled in and their average marks. Include
--students with no enrollments
Select 
 s.studentID
 s.FullName,
 COUNT(e.CourseID) AS NumCourses,
 AVG(e.Marks) AS AvgMarks
From student s
LEFT JOIN Enrollment e ON s.StudnetID=e.studentID
Group BY s.StudentID,s.FullName;


--Find students who scored above 85 in at least one course. Show their FullName and the highest
--mark they have achieved

Select 
 s.FullName,
 MAX(e.Marks)AS HighestMarks
From Student s
Join Enrollment e ON s.StudentID=e.StudentID
Group BY s.StudentID,s.FullName
Having MAX(e.Marks)>85;


--List departments where the average marks across all their courses is below 75. Show Department
--and OverallAvgMarks
Select
 c.Department,
 Avg (e.Marks) AS OverallAvgMarks
From Course c
Join Enrollment e ON c.CourseID=e.CourseID
Order BY c.Department
Having AVG(e.Marks)<75

--Find the top 3 students by total fee they have paid (sum of fees of their enrolled courses). Show
--FullName and TotalFee

Select 
 s.FullName,
 Sum(c.Fee) AS TotalFee
From student s
Join Enrollment e ON s.StudentID=e.StudentID
Join Course c ON e.CourseID=c.CourseID
Group BY s.studentID,s.FullName
Order BY TotalFee DESC
LIMIT 3;